name: rickandmortyangulardart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.3
  meta: ^1.4.0
  http: ^0.12.2
  angular_bloc: ^6.0.1
  rxdart: ^0.27.1
  get_it: ^7.1.4
  json_annotation: ^3.1.1
  chopper: ^3.0.6
  dartz: ^0.9.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
  chopper_generator: ^3.0.6
  json_serializable: ^3.5.1
